// Terraform HCL generator - converts ZoneExport data into proper Terraform configuration files
// Based on cf-terraforming resource mappings (cloudflare provider ~v4)

import type {
  ZoneExport, CFDNSRecord, CFZoneSetting, CFPageRule, CFRuleset, CFRulesetRule,
  CFWorkerScript, CFWorkerRoute, CFWorkerBinding, CFWorkerCustomDomain, CFLoadBalancer, CFPool, CFMonitor,
  CFSpectrumApp, CFCustomCertificate, CFCustomHostname, CFAccessApp, CFAccessPolicy,
  CFFirewallRule, CFRateLimit, CFEmailRoutingRule, CFWaitingRoom, CFTurnstileWidget,
  CFKVNamespace, CFR2Bucket, CFD1Database, CFQueue,
} from './types';
import { isManagedRuleset, isNoOpSetting, READ_ONLY_SETTINGS, BLOCKED_SETTINGS } from './migrate';

// ---------------------------------------------------------------------------
// HCL helpers
// ---------------------------------------------------------------------------

type HclExpr = { __hclExpr: string };
function hclExpr(expr: string): HclExpr {
  return { __hclExpr: expr };
}

/** Escape a string for HCL – double-quotes and backslashes */
function hclString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/** Produce a safe Terraform resource label from an arbitrary id */
function resourceLabel(prefix: string, id: string, index: number): string {
  const sanitized = id.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40);
  return `${prefix}_${sanitized}_${index}`;
}

/** Indent every line of a string by `n` spaces */
function indent(s: string, n: number): string {
  const pad = ' '.repeat(n);
  return s.split('\n').map(l => pad + l).join('\n');
}

/** Render a value as HCL – handles strings, numbers, booleans, arrays, objects */
function hclValue(value: unknown, depth = 0): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return `"${hclString(value)}"`;

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map(v => hclValue(v, depth + 1));
    // Simple arrays on one line if short
    const oneLine = `[${items.join(', ')}]`;
    if (oneLine.length < 80 && !oneLine.includes('\n')) return oneLine;
    return '[\n' + items.map(i => indent(i + ',', (depth + 1) * 2)).join('\n') + '\n' + ' '.repeat(depth * 2) + ']';
  }

  if (typeof value === 'object') {
    // Raw HCL expression
    if ((value as any).__hclExpr && typeof (value as any).__hclExpr === 'string') {
      return (value as any).__hclExpr;
    }
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj);
    if (keys.length === 0) return '{}';
    const lines = keys.map(k => {
      const safeKey = /^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(k) ? k : `"${hclString(k)}"`;
      return `${safeKey} = ${hclValue(obj[k], depth + 1)}`;
    });
    const oneLine = `{ ${lines.join(', ')} }`;
    if (oneLine.length < 80 && !oneLine.includes('\n')) return oneLine;
    return '{\n' + lines.map(l => indent(l, (depth + 1) * 2)).join('\n') + '\n' + ' '.repeat(depth * 2) + '}';
  }

  return `"${String(value)}"`;
}

/** Build a complete resource block */
function resourceBlock(type: string, label: string, attrs: Record<string, unknown>): string {
  const lines: string[] = [`resource "${type}" "${label}" {`];
  for (const [key, val] of Object.entries(attrs)) {
    if (val === undefined || val === null) continue;
    lines.push(`  ${key} = ${hclValue(val, 1)}`);
  }
  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Per-resource generators
// ---------------------------------------------------------------------------

function generateProvider(zoneId: string, accountId: string): string {
  return [
    '# ──────────────────────────────────────────────────────────────────',
    '# Terraform configuration generated by Twilight Zone',
    '# https://github.com/cloudflare/cf-terraforming (resource reference)',
    '# ──────────────────────────────────────────────────────────────────',
    '',
    'terraform {',
    '  required_providers {',
    '    cloudflare = {',
    '      source  = "cloudflare/cloudflare"',
    '      version = "= 5.17.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "cloudflare" {',
    '  api_token = var.cloudflare_api_token',
    '}',
    '',
    'variable "cloudflare_api_token" {',
    '  type      = string',
    '  sensitive = true',
    '}',
    '',
    `variable "zone_id" {`,
    `  default = "${zoneId}"`,
    '}',
    '',
    `variable "account_id" {`,
    `  default = "${accountId}"`,
    '}',
    '',
  ].join('\n');
}

// ── DNS Records ──────────────────────────────────────────────────────

function dnsRecordToTf(r: CFDNSRecord, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    name: r.name,
    type: r.type,
    ttl: r.ttl,
    proxied: r.proxied ?? false,
  };

  // Records with `data` blocks (CAA, SRV, HTTPS, etc.) omit `content`
  if (r.data && Object.keys(r.data).length > 0) {
    attrs.data = r.data;
  } else {
    attrs.content = r.content;
  }

  if (r.priority !== undefined) {
    attrs.priority = r.priority;
  }

  if (r.comment) attrs.comment = r.comment;
  if (r.tags && r.tags.length > 0) attrs.tags = r.tags;
  if (r.settings && Object.keys(r.settings).length > 0) attrs.settings = r.settings;

  return resourceBlock('cloudflare_dns_record', resourceLabel('dns', r.id, idx), attrs);
}

// ── Zone Settings ────────────────────────────────────────────────────

function zoneSettingsToTf(settings: CFZoneSetting[]): string {
  const editable = settings.filter(
    s => s.editable && !READ_ONLY_SETTINGS.has(s.id) && !BLOCKED_SETTINGS.has(s.id) && !isNoOpSetting(s)
  );
  if (editable.length === 0) return '';

  const blocks: string[] = [];
  for (let i = 0; i < editable.length; i++) {
    const s = editable[i];
    const attrs: Record<string, unknown> = {
      zone_id: hclExpr('var.zone_id'),
      setting_id: s.id,
    };
    if (s.id === 'ssl_recommender') {
      // Special case per provider docs: uses `enabled` instead of `value`.
      attrs.enabled = Boolean(s.value);
    } else {
      attrs.value = s.value;
    }
    blocks.push(resourceBlock('cloudflare_zone_setting', resourceLabel('setting', s.id, i), attrs));
  }

  return blocks.join('\n\n');
}

// ── Page Rules ───────────────────────────────────────────────────────

function pageRuleToTf(rule: CFPageRule, idx: number): string {
  const target = rule.targets?.[0]?.constraint?.value || '*';

  // Flatten actions: {id: "ssl", value: "full"} → {ssl: "full"}
  const actionMap: Record<string, unknown> = {};
  for (const a of rule.actions) {
    actionMap[a.id] = a.value ?? true;
  }

  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    target,
    priority: rule.priority,
    status: rule.status,
    actions: actionMap,
  };

  return resourceBlock('cloudflare_page_rule', resourceLabel('pagerule', rule.id, idx), attrs);
}

// ── Rulesets ─────────────────────────────────────────────────────────

function rulesetRuleToObj(rule: CFRulesetRule): Record<string, unknown> {
  const obj: Record<string, unknown> = {
    action: rule.action,
    expression: rule.expression,
    enabled: rule.enabled ?? true,
  };
  if (rule.description) obj.description = rule.description;
  if (rule.action_parameters && Object.keys(rule.action_parameters).length > 0) {
    obj.action_parameters = rule.action_parameters;
  }
  return obj;
}

function rulesetToTf(rs: CFRuleset, idx: number): string {
  const rules = (rs.rules || []).map(rulesetRuleToObj);
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    name: rs.name || 'default',
    description: rs.description || '',
    kind: rs.kind || 'zone',
    phase: rs.phase,
    rules,
  };

  return resourceBlock('cloudflare_ruleset', resourceLabel('ruleset', rs.id, idx), attrs);
}

// ── Workers ──────────────────────────────────────────────────────────

function escapeTerraformTemplateLiterals(s: string): string {
  // Prevent `${...}` / `%{...}` sequences inside heredocs from being interpreted by Terraform.
  return s.replace(/\$\{/g, '$${').replace(/%\{/g, '%%{');
}

function workerBindingToTfV5(b: CFWorkerBinding): Record<string, unknown> | null {
  const base: Record<string, unknown> = { name: b.name, type: b.type };
  switch (b.type) {
    case 'plain_text':
      if (b.text !== undefined) base.text = b.text;
      return base;
    case 'secret_text':
      base.text = 'REPLACE_ME';
      return base;
    case 'kv_namespace':
      if (b.namespace_id) base.namespace_id = b.namespace_id;
      return base;
    case 'r2_bucket':
      if (b.bucket_name) base.bucket_name = b.bucket_name;
      return base;
    case 'd1':
      // Provider expects `id` for the D1 database ID.
      if (b.database_id) base.id = b.database_id;
      return base;
    case 'queue':
      if (b.queue_name) base.queue_name = b.queue_name;
      return base;
    case 'durable_object_namespace':
      if (b.class_name) base.class_name = b.class_name;
      if (b.script_name) base.script_name = b.script_name;
      return base;
    case 'service':
      if (b.service) base.service = b.service;
      if (b.environment) base.environment = b.environment;
      return base;
    default:
      // Unknown binding types are skipped to avoid emitting invalid schemas.
      return null;
  }
}

function workerToTf(w: CFWorkerScript, idx: number): string {
  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    script_name: w.id,
  };

  if (w.script) {
    attrs.content = hclExpr(`<<-EOT\n${escapeTerraformTemplateLiterals(w.script)}\nEOT`);
  }

  if (w.script_format === 'modules' && w.main_module) {
    attrs.main_module = w.main_module;
  }

  if (w.bindings && w.bindings.length > 0) {
    const bindings = w.bindings
      .map(workerBindingToTfV5)
      .filter(Boolean) as Record<string, unknown>[];
    if (bindings.length > 0) {
      attrs.bindings = bindings;
    }
  }

  return resourceBlock('cloudflare_workers_script', resourceLabel('worker', w.id, idx), attrs);
}

function workerRouteToTf(r: CFWorkerRoute, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    pattern: r.pattern,
    script: r.script,
  };
  return resourceBlock('cloudflare_workers_route', resourceLabel('route', r.id, idx), attrs);
}

function workerCustomDomainToTf(cd: CFWorkerCustomDomain, idx: number): string {
  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    zone_id: hclExpr('var.zone_id'),
    hostname: cd.hostname,
    service: cd.service,
  };
  if (cd.environment) attrs.environment = cd.environment;
  return resourceBlock('cloudflare_workers_custom_domain', resourceLabel('wcd', cd.id, idx), attrs);
}

// ── Load Balancers ───────────────────────────────────────────────────

function monitorToTf(m: CFMonitor, idx: number): string {
  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    description: m.description,
    type: m.type,
    method: m.method,
    path: m.path,
    port: m.port,
    timeout: m.timeout,
    retries: m.retries,
    interval: m.interval,
    expected_codes: m.expected_codes,
    expected_body: m.expected_body,
    follow_redirects: m.follow_redirects,
    allow_insecure: m.allow_insecure,
  };
  if (m.header) attrs.header = m.header;

  return resourceBlock('cloudflare_load_balancer_monitor', resourceLabel('monitor', m.id, idx), attrs);
}

function poolToTf(p: CFPool, idx: number): string {
  const origins = p.origins.map(o => ({
    name: o.name,
    address: o.address,
    enabled: o.enabled,
    weight: o.weight,
    ...(o.header ? { header: o.header } : {}),
  }));

  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    name: p.name,
    description: p.description,
    enabled: p.enabled,
    minimum_origins: p.minimum_origins,
    origins,
  };
  if (p.notification_email) attrs.notification_email = p.notification_email;
  // monitor is an ID reference – in a real config this would use a resource reference
  if (p.monitor) attrs.monitor = p.monitor;

  return resourceBlock('cloudflare_load_balancer_pool', resourceLabel('pool', p.id, idx), attrs);
}

function loadBalancerToTf(lb: CFLoadBalancer, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    name: lb.name,
    description: lb.description || '',
    default_pools: lb.default_pools,
    fallback_pool: lb.fallback_pool,
    proxied: lb.proxied,
    ttl: lb.ttl,
    steering_policy: lb.steering_policy,
    session_affinity: lb.session_affinity,
    session_affinity_ttl: lb.session_affinity_ttl,
  };
  if (lb.rules && lb.rules.length > 0) {
    attrs.rules = lb.rules.map(r => ({
      name: r.name,
      condition: r.condition,
      disabled: r.disabled,
      priority: r.priority,
      terminates: r.terminates,
      ...(r.fixed_response ? { fixed_response: r.fixed_response } : {}),
      ...(r.overrides ? { overrides: r.overrides } : {}),
    }));
  }

  return resourceBlock('cloudflare_load_balancer', resourceLabel('lb', lb.id, idx), attrs);
}

// ── Spectrum ─────────────────────────────────────────────────────────

function spectrumAppToTf(app: CFSpectrumApp, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    protocol: app.protocol,
    dns: { type: app.dns.type, name: app.dns.name },
    origin_dns: { name: app.origin_dns.name },
    origin_port: app.origin_port,
    tls: app.tls,
    proxy_protocol: app.proxy_protocol,
    ip_firewall: app.ip_firewall,
    edge_ips: app.edge_ips,
  };
  return resourceBlock('cloudflare_spectrum_application', resourceLabel('spectrum', app.id, idx), attrs);
}

// ── Custom Certificates ──────────────────────────────────────────────

function customCertToTf(cert: CFCustomCertificate, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    certificate: '# Paste your certificate PEM here',
    private_key: '# Paste your private key PEM here',
    bundle_method: cert.bundle_method,
  };
  return resourceBlock('cloudflare_custom_ssl', resourceLabel('cert', cert.id, idx), attrs);
}

// ── Custom Hostnames ─────────────────────────────────────────────────

function customHostnameToTf(ch: CFCustomHostname, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    hostname: ch.hostname,
    ssl: {
      method: ch.ssl.method,
      type: ch.ssl.type,
    },
  };
  if (ch.custom_origin_server) attrs.custom_origin_server = ch.custom_origin_server;

  return resourceBlock('cloudflare_custom_hostname', resourceLabel('chost', ch.id, idx), attrs);
}

// ── Access Applications & Policies ───────────────────────────────────

function parseAccessPolicyCompositeId(id: string): { appId: string | null; policyId: string } {
  const parts = (id || '').split('/');
  if (parts.length >= 2) return { appId: parts[0] || null, policyId: parts.slice(1).join('/') };
  return { appId: null, policyId: id };
}

function accessPolicyToTf(policy: CFAccessPolicy, idx: number): string {
  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    decision: policy.decision,
    name: policy.name,
  };
  if (policy.include && policy.include.length > 0) attrs.include = policy.include;
  if (policy.exclude && policy.exclude.length > 0) attrs.exclude = policy.exclude;
  if (policy.require && policy.require.length > 0) attrs.require = policy.require;
  return resourceBlock('cloudflare_zero_trust_access_policy', resourceLabel('access_policy', policy.id, idx), attrs);
}

function accessAppToTf(
  app: CFAccessApp,
  idx: number,
  policyRefs: Array<{ policyLabel: string; precedence: number }>,
): string {
  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    name: app.name,
    domain: app.domain,
    type: app.type,
    session_duration: app.session_duration,
    allowed_idps: app.allowed_idps,
    auto_redirect_to_identity: app.auto_redirect_to_identity,
  };

  if (policyRefs.length > 0) {
    attrs.policies = policyRefs.map(p => ({
      id: hclExpr(`cloudflare_zero_trust_access_policy.${p.policyLabel}.id`),
      precedence: p.precedence,
    }));
  }

  return resourceBlock('cloudflare_zero_trust_access_application', resourceLabel('access_app', app.id, idx), attrs);
}

// ── Firewall Rules ───────────────────────────────────────────────────

function firewallRuleToTf(rule: CFFirewallRule, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    action: { mode: rule.action },
    filter: {
      expression: rule.filter?.expression || '',
      paused: rule.filter?.paused ?? false,
      description: rule.description || '',
    },
  };

  return resourceBlock('cloudflare_firewall_rule', resourceLabel('fw', rule.id, idx), attrs);
}

// ── Rate Limits ──────────────────────────────────────────────────────

function rateLimitToTf(rl: CFRateLimit, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    threshold: rl.threshold,
    period: rl.period,
    match: rl.match,
    action: rl.action,
  };
  return resourceBlock('cloudflare_rate_limit', resourceLabel('ratelimit', rl.id, idx), attrs);
}

// ── Email Routing ────────────────────────────────────────────────────

function emailRuleToTf(rule: CFEmailRoutingRule, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    name: rule.name,
    enabled: rule.enabled,
    priority: rule.priority,
    matchers: rule.matchers,
    actions: rule.actions,
  };
  return resourceBlock('cloudflare_email_routing_rule', resourceLabel('email', rule.tag || rule.id, idx), attrs);
}

// ── Waiting Rooms ────────────────────────────────────────────────────

function waitingRoomToTf(wr: CFWaitingRoom, idx: number): string {
  const attrs: Record<string, unknown> = {
    zone_id: hclExpr('var.zone_id'),
    name: wr.name,
    description: wr.description || '',
    host: wr.host,
    path: wr.path || '/',
    queue_all: wr.queue_all,
    new_users_per_minute: wr.new_users_per_minute,
    total_active_users: wr.total_active_users,
    session_duration: wr.session_duration,
    disable_session_renewal: wr.disable_session_renewal,
    suspended: wr.suspended,
    json_response_enabled: wr.json_response_enabled,
    default_template_language: wr.default_template_language,
  };
  if (wr.custom_page_html) attrs.custom_page_html = wr.custom_page_html;
  if (wr.cookie_suffix) attrs.cookie_suffix = wr.cookie_suffix;
  if (wr.additional_routes && wr.additional_routes.length > 0) attrs.additional_routes = wr.additional_routes;
  if (wr.cookie_attributes) attrs.cookie_attributes = wr.cookie_attributes;

  return resourceBlock('cloudflare_waiting_room', resourceLabel('waitroom', wr.id, idx), attrs);
}

// ── Turnstile Widgets ────────────────────────────────────────────────

function turnstileToTf(tw: CFTurnstileWidget, idx: number): string {
  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    name: tw.name,
    domains: tw.domains,
    mode: tw.mode,
    region: tw.region,
    bot_fight_mode: tw.bot_fight_mode,
    offlabel: tw.offlabel,
  };
  return resourceBlock('cloudflare_turnstile_widget', resourceLabel('turnstile', tw.sitekey, idx), attrs);
}

// ── Storage resources ────────────────────────────────────────────────

function kvNamespaceToTf(kv: CFKVNamespace, idx: number): string {
  return resourceBlock('cloudflare_workers_kv_namespace', resourceLabel('kv', kv.id, idx), {
    account_id: hclExpr('var.account_id'),
    title: kv.title,
  });
}

function r2BucketToTf(bucket: CFR2Bucket, idx: number): string {
  const attrs: Record<string, unknown> = {
    account_id: hclExpr('var.account_id'),
    name: bucket.name,
  };
  if (bucket.location) attrs.location = bucket.location;
  return resourceBlock('cloudflare_r2_bucket', resourceLabel('r2', bucket.name, idx), attrs);
}

function d1DatabaseToTf(db: CFD1Database, idx: number): string {
  return resourceBlock('cloudflare_d1_database', resourceLabel('d1', db.uuid, idx), {
    account_id: hclExpr('var.account_id'),
    name: db.name,
  });
}

function queueToTf(q: CFQueue, idx: number): string {
  return resourceBlock('cloudflare_queue', resourceLabel('queue', q.queue_id, idx), {
    account_id: hclExpr('var.account_id'),
    queue_name: q.queue_name,
  });
}

// ---------------------------------------------------------------------------
// File generators – each returns { filename, content }
// ---------------------------------------------------------------------------

export interface TerraformFile {
  filename: string;
  content: string;
}

/** Generate the main provider + variables file */
function generateMainTf(zoneId: string, accountId: string, zoneName: string): TerraformFile {
  return {
    filename: 'main.tf',
    content: generateProvider(zoneId, accountId) + [
      `# Zone: ${zoneName}`,
      resourceBlock('cloudflare_zone', 'this', {
        account: { id: hclExpr('var.account_id') },
        name: zoneName,
        type: 'full',
      }),
      '',
    ].join('\n'),
  };
}

function generateDnsTf(records: CFDNSRecord[]): TerraformFile | null {
  if (records.length === 0) return null;
  const content = [
    '# DNS Records',
    `# Total: ${records.length} records`,
    '',
    ...records.map((r, i) => dnsRecordToTf(r, i)),
  ].join('\n\n');
  return { filename: 'dns.tf', content };
}

function generateSettingsTf(settings: CFZoneSetting[]): TerraformFile | null {
  const block = zoneSettingsToTf(settings);
  if (!block) return null;
  return {
    filename: 'settings.tf',
    content: ['# Zone Settings (cloudflare_zone_setting)', '', block].join('\n'),
  };
}

function generatePageRulesTf(rules: CFPageRule[]): TerraformFile | null {
  if (rules.length === 0) return null;
  const content = [
    '# Page Rules',
    `# Total: ${rules.length} rules`,
    '',
    ...rules.map((r, i) => pageRuleToTf(r, i)),
  ].join('\n\n');
  return { filename: 'page_rules.tf', content };
}

function generateRulesetsTf(rulesets: CFRuleset[]): TerraformFile | null {
  // Filter out managed rulesets
  const custom = rulesets.filter(rs => !isManagedRuleset(rs));
  if (custom.length === 0) return null;
  const content = [
    '# Rulesets (WAF, Transforms, Cache Rules, Redirect Rules, etc.)',
    `# Total: ${custom.length} rulesets`,
    '',
    ...custom.map((rs, i) => rulesetToTf(rs, i)),
  ].join('\n\n');
  return { filename: 'rulesets.tf', content };
}

function generateWorkersTf(workers: CFWorkerScript[], routes: CFWorkerRoute[], customDomains: CFWorkerCustomDomain[]): TerraformFile | null {
  const tfWorkers = workers.filter(w => (w as any).isAccountLevel !== true && Boolean((w as any).script));
  if (tfWorkers.length === 0 && routes.length === 0 && customDomains.length === 0) return null;
  const parts: string[] = [
    '# Workers & Routes',
    `# Workers: ${tfWorkers.length} (zone-related with fetched code), Routes: ${routes.length}, Custom Domains: ${customDomains.length}`,
    '',
  ];
  for (let i = 0; i < tfWorkers.length; i++) {
    parts.push(workerToTf(tfWorkers[i], i));
    parts.push('');
  }
  for (let i = 0; i < routes.length; i++) {
    parts.push(workerRouteToTf(routes[i], i));
    parts.push('');
  }
  for (let i = 0; i < customDomains.length; i++) {
    parts.push(workerCustomDomainToTf(customDomains[i], i));
    parts.push('');
  }
  return { filename: 'workers.tf', content: parts.join('\n') };
}

function generateLoadBalancersTf(lbs: CFLoadBalancer[], pools: CFPool[], monitors: CFMonitor[]): TerraformFile | null {
  if (lbs.length === 0 && pools.length === 0 && monitors.length === 0) return null;
  const parts: string[] = [
    '# Load Balancers',
    `# Monitors: ${monitors.length}, Pools: ${pools.length}, Load Balancers: ${lbs.length}`,
    '',
  ];
  for (let i = 0; i < monitors.length; i++) {
    parts.push(monitorToTf(monitors[i], i));
    parts.push('');
  }
  for (let i = 0; i < pools.length; i++) {
    parts.push(poolToTf(pools[i], i));
    parts.push('');
  }
  for (let i = 0; i < lbs.length; i++) {
    parts.push(loadBalancerToTf(lbs[i], i));
    parts.push('');
  }
  return { filename: 'load_balancers.tf', content: parts.join('\n') };
}

function generateSecurityTf(
  firewallRules: CFFirewallRule[],
  rateLimits: CFRateLimit[],
  accessApps: CFAccessApp[],
  accessPolicies: CFAccessPolicy[]
): TerraformFile | null {
  if (firewallRules.length === 0 && rateLimits.length === 0 && accessApps.length === 0) return null;
  const parts: string[] = [
    '# Security – Firewall Rules, Rate Limits, Access Applications',
    '',
  ];
  for (let i = 0; i < firewallRules.length; i++) {
    parts.push(firewallRuleToTf(firewallRules[i], i));
    parts.push('');
  }
  for (let i = 0; i < rateLimits.length; i++) {
    parts.push(rateLimitToTf(rateLimits[i], i));
    parts.push('');
  }

  // Zero Trust Access Policies (account-level) must exist before applications can reference them.
  const policyLabelByCompositeId = new Map<string, string>();
  if (accessPolicies.length > 0) {
    parts.push('# Zero Trust Access Policies');
    parts.push('');
    for (let pi = 0; pi < accessPolicies.length; pi++) {
      const p = accessPolicies[pi];
      const label = resourceLabel('access_policy', p.id, pi);
      policyLabelByCompositeId.set(p.id, label);
      parts.push(accessPolicyToTf(p, pi));
      parts.push('');
    }
  }

  if (accessApps.length > 0) {
    parts.push('# Zero Trust Access Applications');
    parts.push('');
    for (let i = 0; i < accessApps.length; i++) {
      const app = accessApps[i];
      const refs = accessPolicies
        .filter(p => parseAccessPolicyCompositeId(p.id).appId === app.id)
        .map(p => ({ policyLabel: policyLabelByCompositeId.get(p.id) || resourceLabel('access_policy', p.id, 0), precedence: p.precedence }))
        .sort((a, b) => a.precedence - b.precedence);
      parts.push(accessAppToTf(app, i, refs));
      parts.push('');
    }
  }
  return { filename: 'security.tf', content: parts.join('\n') };
}

function generateExtraTf(
  spectrumApps: CFSpectrumApp[],
  customCerts: CFCustomCertificate[],
  customHostnames: CFCustomHostname[],
  emailRules: CFEmailRoutingRule[],
  waitingRooms: CFWaitingRoom[],
  turnstileWidgets: CFTurnstileWidget[]
): TerraformFile | null {
  const total = spectrumApps.length + customCerts.length + customHostnames.length +
    emailRules.length + waitingRooms.length + turnstileWidgets.length;
  if (total === 0) return null;

  const parts: string[] = [
    '# Additional Resources',
    `# Spectrum: ${spectrumApps.length}, Certificates: ${customCerts.length}, ` +
    `Custom Hostnames: ${customHostnames.length}, Email Rules: ${emailRules.length}, ` +
    `Waiting Rooms: ${waitingRooms.length}, Turnstile: ${turnstileWidgets.length}`,
    '',
  ];

  for (let i = 0; i < spectrumApps.length; i++) { parts.push(spectrumAppToTf(spectrumApps[i], i)); parts.push(''); }
  for (let i = 0; i < customCerts.length; i++) { parts.push(customCertToTf(customCerts[i], i)); parts.push(''); }
  for (let i = 0; i < customHostnames.length; i++) { parts.push(customHostnameToTf(customHostnames[i], i)); parts.push(''); }
  for (let i = 0; i < emailRules.length; i++) { parts.push(emailRuleToTf(emailRules[i], i)); parts.push(''); }
  for (let i = 0; i < waitingRooms.length; i++) { parts.push(waitingRoomToTf(waitingRooms[i], i)); parts.push(''); }
  for (let i = 0; i < turnstileWidgets.length; i++) { parts.push(turnstileToTf(turnstileWidgets[i], i)); parts.push(''); }

  return { filename: 'extra.tf', content: parts.join('\n') };
}

function generateStorageTf(
  kvNamespaces: CFKVNamespace[],
  r2Buckets: CFR2Bucket[],
  d1Databases: CFD1Database[],
  queues: CFQueue[]
): TerraformFile | null {
  const total = kvNamespaces.length + r2Buckets.length + d1Databases.length + queues.length;
  if (total === 0) return null;

  const parts: string[] = [
    '# Storage Resources (Account-level)',
    `# KV: ${kvNamespaces.length}, R2: ${r2Buckets.length}, D1: ${d1Databases.length}, Queues: ${queues.length}`,
    '',
  ];

  for (let i = 0; i < kvNamespaces.length; i++) { parts.push(kvNamespaceToTf(kvNamespaces[i], i)); parts.push(''); }
  for (let i = 0; i < r2Buckets.length; i++) { parts.push(r2BucketToTf(r2Buckets[i], i)); parts.push(''); }
  for (let i = 0; i < d1Databases.length; i++) { parts.push(d1DatabaseToTf(d1Databases[i], i)); parts.push(''); }
  for (let i = 0; i < queues.length; i++) { parts.push(queueToTf(queues[i], i)); parts.push(''); }

  return { filename: 'storage.tf', content: parts.join('\n') };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Generate all Terraform files from a ZoneExport */
export function generateTerraformFiles(data: ZoneExport): TerraformFile[] {
  const zoneId = data.zone.id;
  const accountId = data.zone.account.id;
  const zoneName = data.zone.name;

  const files: TerraformFile[] = [
    generateMainTf(zoneId, accountId, zoneName),
  ];

  const optional: (TerraformFile | null)[] = [
    generateDnsTf(data.dnsRecords),
    generateSettingsTf(data.settings),
    generatePageRulesTf(data.pageRules),
    generateRulesetsTf(data.rulesets),
    generateWorkersTf(
      data.workers,
      data.workerRoutes,
      (data.workerCustomDomains || []).filter(cd => cd.zone_id === data.zone.id)
    ),
    generateLoadBalancersTf(data.loadBalancers, data.pools, data.monitors),
    generateSecurityTf(data.firewallRules, data.rateLimits, data.accessApps, data.accessPolicies),
    generateExtraTf(
      data.spectrumApps, data.customCertificates, data.customHostnames,
      data.emailRoutingRules, data.waitingRooms, data.turnstileWidgets
    ),
    generateStorageTf(data.kvNamespaces, data.r2Buckets, data.d1Databases, data.queues),
  ];

  for (const f of optional) {
    if (f) files.push(f);
  }

  return files;
}

/** Generate a single concatenated .tf file (for simple download) */
export function generateTerraformBundle(data: ZoneExport): string {
  return generateTerraformFiles(data)
    .map(f => `# ═══ ${f.filename} ${'═'.repeat(Math.max(0, 60 - f.filename.length))}\n\n${f.content}`)
    .join('\n\n');
}

/** Generate a summary of what would be generated */
export function terraformExportSummary(data: ZoneExport): {
  files: { filename: string; resourceCount: number }[];
  totalResources: number;
} {
  const customRulesets = data.rulesets.filter(rs => !isManagedRuleset(rs));
  const editableSettings = data.settings.filter(
    s => s.editable && !READ_ONLY_SETTINGS.has(s.id) && !BLOCKED_SETTINGS.has(s.id) && !isNoOpSetting(s)
  );
  const tfWorkersCount = data.workers.filter(w => (w as any).isAccountLevel !== true && Boolean((w as any).script)).length;

  const counts: { filename: string; resourceCount: number }[] = [
    { filename: 'main.tf', resourceCount: 1 },
  ];

  if (data.dnsRecords.length > 0) counts.push({ filename: 'dns.tf', resourceCount: data.dnsRecords.length });
  if (editableSettings.length > 0) counts.push({ filename: 'settings.tf', resourceCount: editableSettings.length });
  if (data.pageRules.length > 0) counts.push({ filename: 'page_rules.tf', resourceCount: data.pageRules.length });
  if (customRulesets.length > 0) counts.push({ filename: 'rulesets.tf', resourceCount: customRulesets.length });
  const wcdCount = (data.workerCustomDomains || []).filter(cd => cd.zone_id === data.zone.id).length;
  if (tfWorkersCount > 0 || data.workerRoutes.length > 0 || wcdCount > 0) {
    counts.push({ filename: 'workers.tf', resourceCount: tfWorkersCount + data.workerRoutes.length + wcdCount });
  }
  if (data.loadBalancers.length + data.pools.length + data.monitors.length > 0) {
    counts.push({ filename: 'load_balancers.tf', resourceCount: data.loadBalancers.length + data.pools.length + data.monitors.length });
  }
  const secCount = data.firewallRules.length + data.rateLimits.length + data.accessApps.length + data.accessPolicies.length;
  if (secCount > 0) counts.push({ filename: 'security.tf', resourceCount: secCount });
  const extraCount = data.spectrumApps.length + data.customCertificates.length + data.customHostnames.length +
    data.emailRoutingRules.length + data.waitingRooms.length + data.turnstileWidgets.length;
  if (extraCount > 0) counts.push({ filename: 'extra.tf', resourceCount: extraCount });
  const storageCount = data.kvNamespaces.length + data.r2Buckets.length + data.d1Databases.length + data.queues.length;
  if (storageCount > 0) counts.push({ filename: 'storage.tf', resourceCount: storageCount });

  return {
    files: counts,
    totalResources: counts.reduce((s, c) => s + c.resourceCount, 0),
  };
}

// ---------------------------------------------------------------------------
// Terraform upload (parse & apply) helpers
// ---------------------------------------------------------------------------

/** Minimal HCL parser – extracts resource blocks from .tf file content */
export interface ParsedTfResource {
  type: string;      // e.g. "cloudflare_record"
  label: string;     // e.g. "dns_abc123_0"
  body: string;      // raw HCL body between { }
}

/**
 * Parse resource blocks from HCL text.
 * This is a best-effort parser for the HCL subset we generate.
 */
export function parseTerraformResources(hcl: string): ParsedTfResource[] {
  const resources: ParsedTfResource[] = [];
  const regex = /resource\s+"([^"]+)"\s+"([^"]+)"\s*\{/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(hcl)) !== null) {
    const type = match[1];
    const label = match[2];
    const startIdx = match.index + match[0].length;

    // Find matching closing brace (handle nested braces)
    let depth = 1;
    let i = startIdx;
    while (i < hcl.length && depth > 0) {
      if (hcl[i] === '{') depth++;
      else if (hcl[i] === '}') depth--;
      i++;
    }

    const body = hcl.slice(startIdx, i - 1).trim();
    resources.push({ type, label, body });
  }

  return resources;
}

/** Extract simple key=value attributes from an HCL block body (top-level only) */
export function extractAttributes(body: string): Record<string, string> {
  const attrs: Record<string, string> = {};
  // Match lines like:  key = "value"  or  key = value  or  key = true
  const lines = body.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    const m = trimmed.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/);
    if (m) {
      const key = m[1];
      let val = m[2].trim();
      // Strip quotes from string values
      if (val.startsWith('"') && val.endsWith('"')) {
        val = val.slice(1, -1);
      }
      attrs[key] = val;
    }
  }
  return attrs;
}
